-- MySQL Script generated by MySQL Workbench
-- Sat Dec  4 11:05:08 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db02r
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db02r
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db02r` DEFAULT CHARACTER SET utf8 ;
USE `db02r` ;

-- -----------------------------------------------------
-- Table `db02r`.`gift_certificate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db02r`.`gift_certificate` (
                                                          `id` INT NOT NULL AUTO_INCREMENT,
                                                          `name` VARCHAR(45) NOT NULL,
                                                          `description` VARCHAR(45) NOT NULL,
                                                          `price` DOUBLE NOT NULL,
                                                          `duration` INT NOT NULL,
                                                          `create_date` TIMESTAMP(6) NULL,
                                                          `last_update_date` TIMESTAMP(6) NULL,
                                                          PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db02r`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db02r`.`tag` (
                                             `id` INT NOT NULL AUTO_INCREMENT,
                                             `name` VARCHAR(45) NOT NULL,
                                             PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db02r`.`gift_certificate_m2m_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db02r`.`gift_certificate_m2m_tag` (
                                                                  `gift_certificate_id` INT NOT NULL,
                                                                  `tag_id` INT NOT NULL,
                                                                  PRIMARY KEY (`gift_certificate_id`, `tag_id`),
                                                                  INDEX `fk_gift_certificate_has_tag_tag1_idx` (`tag_id` ASC) VISIBLE,
                                                                  INDEX `fk_gift_certificate_has_tag_gift_certificate_idx` (`gift_certificate_id` ASC) VISIBLE,
                                                                  CONSTRAINT `fk_gift_certificate_has_tag_gift_certificate`
                                                                      FOREIGN KEY (`gift_certificate_id`)
                                                                          REFERENCES `db02r`.`gift_certificate` (`id`)
                                                                          ON DELETE CASCADE
                                                                          ON UPDATE NO ACTION,
                                                                  CONSTRAINT `fk_gift_certificate_has_tag_tag1`
                                                                      FOREIGN KEY (`tag_id`)
                                                                          REFERENCES `db02r`.`tag` (`id`)
                                                                          ON DELETE CASCADE
                                                                          ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
